services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "echo", "true"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
